services:
  # ⚡ Global Code Executor
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    networks:
      - executor-network
    deploy:
      resources:
        limits:
          memory: "500M"
          cpus: "1"

networks:
  executor-network:
    driver: bridge
